version: "3.4"
services:

  nginx:
    image: nginx:alpine
    container_name: symfony_eventsourcing_webserver
    working_dir: /application
    volumes:
      - ../../../:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    build: docker/php
    environment:
      PHP_IDE_CONFIG: "serverName=my.docker"
    container_name: symfony_eventsourcing_fpm
    working_dir: /application
    volumes:
      - ../../../:/application
      - ./phpdocker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    mysql:
      image: mysql:5.7
      container_name: symfony_eventsourcing_mysql
      working_dir: /application
      volumes:
        - ../../../:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8082:3306"

    projection_product:
      image: prooph/php:7.2-cli
      container_name: symfony_eventsourcing_projection_product
      working_dir: /application
      volumes:
        - ../../../:/application
      depends_on:
        - mysql
      command: php bin/console event-store:projection:run product_projection

    memcached:
      image: memcached:alpine
      container_name: symfony_eventsourcing_memcached

    redis:
      image: redis:alpine
      container_name: symfony_eventsourcing_redis

    blackfire:
      image: blackfire/blackfire
      container_name: symfony_eventsourcing_projection_blackfire
      depends_on:
        - php
      environment:
        BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
        BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
        BLACKFIRE_LOG_LEVEL: 4
      ports:
        - "8707:8707"
